#ifndef CLP_TOKEN_H
#define CLP_TOKEN_H

#include <stdlib.h>

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

typedef enum {
    // Single-character tokens
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN, TOKEN_LEFT_BRACE,
    TOKEN_RIGHT_BRACE, TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS,
    TOKEN_PLUS, TOKEN_PERCENT, TOKEN_CARET, TOKEN_PIPE,
    TOKEN_AMP, TOKEN_TILDE, TOKEN_SEMICOLON, TOKEN_LEFT_BRACKET,
    TOKEN_RIGHT_BRACKET,

    // One or two character tokens
    TOKEN_LESS, TOKEN_GREATER, TOKEN_LESS_LESS, TOKEN_GREATER_GREATER,
    TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS, TOKEN_STAR,
    TOKEN_STAR_STAR, TOKEN_FSLASH, TOKEN_FSLASH_FSLASH,
    TOKEN_BANG, TOKEN_BANG_EQUAL, TOKEN_EQUAL,
    TOKEN_EQUAL_EQUAL, TOKEN_EQUAL_EQUAL_EQUAL,
    TOKEN_BANG_EQUAL_EQUAL, TOKEN_EQUAL_EQUAL_BANG,
    TOKEN_LESS_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_MINUS_EQUAL,
    TOKEN_PLUS_EQUAL, TOKEN_STAR_EQUAL, TOKEN_FSLASH_EQUAL,
    TOKEN_PERCENT_EQUAL, TOKEN_STAR_STAR_EQUAL,
    TOKEN_LESS_LESS_EQUAL, TOKEN_GREATER_GREATER_EQUAL,
    TOKEN_AMP_EQUAL, TOKEN_PIPE_EQUAL, TOKEN_CARET_EQUAL,
    TOKEN_TILDE_EQUAL,

    // Literals
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,
    TOKEN_CHARACTER,

    // Keywords
    TOKEN_DEF, TOKEN_CLASS, TOKEN_PUBLIC, TOKEN_PRIVATE,
    TOKEN_PROTECTED, TOKEN_IMPLEMENTS, TOKEN_STATIC,
    TOKEN_UNDEFINED, TOKEN_TRUE, TOKEN_FALSE, TOKEN_MODULE,
    TOKEN_IF, TOKEN_ELSE, TOKEN_FOR, TOKEN_WHILE, TOKEN_AND,
    TOKEN_OR, TOKEN_XOR, TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS,
    TOKEN_NEW,

    TOKEN_ERROR, TOKEN_EOF
} TokenType;

typedef struct Token {
    TokenType type;
    char* start; // pointer to start location in source buffer of the lexeme
    size_t length;
    int line;
} Token;

#endif
